[general]
show_welcome = false

[display.quality]
surface_scale = 1

[display.window]
fullscreen_on_startup = true

[general.misc]
skip_boot_anim = true

[input.bindings]
port1 = '03000000de280000ff11000001000000'

[display.ui]
show_menubar = false
scale = 2
fit = 'stretch'

[sys]
mem_limit = '128'

[sys.files]
bootrom_path = '/storage/roms/bios/xemu/bios/mcpx_1.0.bin'
flashrom_path = '/storage/roms/bios/xemu/bios/Complex_4627v1.03.bin'
eeprom_path = '/storage/roms/bios/xemu/eeprom/eeprom.bin'
hdd_path = '/storage/roms/bios/xemu/hdd/xbox_hdd.qcow2'
