/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BINDIR "/usr/bin"

#define BUILD_COLOR_LCMS 0

#define BUILD_DRM_COMPOSITOR 1

#define BUILD_DRM_GBM 1

#define BUILD_DRM_VIRTUAL 1

#define BUILD_PIPEWIRE_COMPOSITOR 1

#define BUILD_WAYLAND_COMPOSITOR 1

#define BUILD_XWAYLAND 1

#define DATADIR "/usr/share"

#define EGL_NO_PLATFORM_SPECIFIC_TYPES 1

#define EGL_NO_X11 1

#define ENABLE_EGL 1

#define ENABLE_JUNIT_XML 0

#define HAVE_BUILTIN_BSWAP32 1

#define HAVE_BUILTIN_CLZ 1

#define HAVE_BUILTIN_POPCOUNT 1

#define HAVE_GBM_BO_CREATE_WITH_MODIFIERS2 1

#define HAVE_INITGROUPS 1

#define HAVE_JPEG 1

#define HAVE_LCMS 1

#define HAVE_LINUX_SYNC_FILE_H 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_MKOSTEMP 1

#define HAVE_PANGO 1

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_STRCHRNUL 1

#define HAVE_UNREACHABLE 1

#define HAVE_WEBP 1

#define HAVE_XKBCOMMON_COMPOSE 1

#define HAVE_XWAYLAND_LISTENFD 1

#define LIBEXECDIR "/usr/lib"

#define LIBWESTON_MODULEDIR "/usr/lib/libweston-14"

#define MAJOR_IN_SYSMACROS 1

#define MESA_EGL_NO_X11_HEADERS 1

#define MODULEDIR "/usr/lib/weston"

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/wayland/weston/issues/"

#define PACKAGE_STRING "weston 14.0.0"

#define PACKAGE_URL "https://wayland.freedesktop.org"

#define PACKAGE_VERSION "14.0.0"

#define VERSION "14.0.0"

#define WESTON_NATIVE_BACKEND "drm"

#define WESTON_SHELL_CLIENT "weston-desktop-shell"

#define XSERVER_PATH "/usr/bin/Xwayland"

#define _ALL_SOURCE 1

#define _GNU_SOURCE 1

